export const seedDetails = {
  Tomato: {
    ind:0,
    max_temp: 30,
    min_temp: 10,
    max_brightness_level: 3.0,
    min_brightness_level: 0.8,
    max_humidity: 70,
    min_humidity: 50,
    seed_description: `Tomatoes thrive in warm climates with ample sunlight and moderate humidity. They require well-drained, fertile soil and regular watering. Proper planting, staking, pruning, and fertilization are essential for healthy growth and abundant fruit production. Harvesting at the right time and proper storage help maintain the quality of the harvested tomatoes. With proper care, tomato plants can yield a delicious and bountiful harvest.`,
  },
    Apple: {
      ind:1,
      max_temp: 30,
      min_temp: 10,
      max_brightness_level: 3.0,
      min_brightness_level: 0.5,
      max_humidity: 70,
      min_humidity: 40,
      seed_description: `Apple trees thrive in temperate climates with ample sunlight and moderate humidity. They require well-drained, fertile soil and regular watering. Proper planting, pruning, and fertilization are essential for healthy growth and abundant fruit production. Regular monitoring for pests and diseases helps maintain tree health. By following these guidelines, you can enjoy a bountiful harvest of delicious apples year after year.`,
    },
    Watermelon: {
      ind:2,
      max_temp: 35,
      min_temp: 18,
      max_brightness_level: 3.5,
      min_brightness_level: 1.0,
      max_humidity: 70,
      min_humidity: 30,
      seed_description: `Watermelons thrive in warm climates with ample sunlight and moderate humidity. They require well-drained, fertile soil and regular watering. Proper planting, spacing, and fertilization are essential for healthy growth and abundant fruit production. Regular monitoring for pests and diseases helps maintain tree health. By following these guidelines, you can enjoy a delicious harvest of sweet and refreshing watermelons.`,
    },
    Carrot: {
      ind:3,
      max_temp: 24,
      min_temp: 6,
      max_brightness_level: 2.5,
      min_brightness_level: 0.5,
      max_humidity: 80,
      min_humidity: 30,
      seed_description: `Carrots thrive in cooler climates with moderate sunlight and humidity. They require well-drained, loose soil and consistent watering. Planting in early spring or late summer and regular thinning and weeding are essential for optimal growth. Harvesting at the desired size and proper storage help maintain the quality of the harvested carrots. With proper care, carrots can be a rewarding and low-maintenance crop.`,
    },
    Chilli: {
      ind:4,
      max_temp: 35,
      min_temp: 15,
      max_brightness_level: 3.0,
      min_brightness_level: 1.0,
      max_humidity: 70,
      min_humidity: 40,
      seed_description: `Chili peppers thrive in warm climates with ample sunlight and moderate humidity. They require well-drained, fertile soil and regular watering. Proper planting, spacing, pruning, and fertilization are essential for healthy growth and abundant fruit production. Regular monitoring for pests and diseases helps maintain plant health. By following these guidelines, you can enjoy a delicious harvest of spicy and flavorful chili peppers.`,
    },
    Grape: {
      ind:5,
      max_temp: 35,
      min_temp: 15,
      max_brightness_level: 3.5,
      min_brightness_level: 1.0,
      max_humidity: 70,
      min_humidity: 40,
      seed_description: `Grapevines thrive in temperate climates with ample sunlight and moderate humidity. They require well-drained, fertile soil and regular watering. Proper planting, pruning, and fertilization are essential for healthy growth and abundant fruit production. Regular monitoring for pests and diseases helps maintain vine health. By following these guidelines, you can enjoy a delicious harvest of sweet, juicy grapes for fresh eating or winemaking.`,
    },
    Lemon: {
      ind:6,
      max_temp: 35,
      min_temp: 15,
      max_brightness_level: 3.5,
      min_brightness_level: 1.0,
      max_humidity: 70,
      min_humidity: 40,
      seed_description: `Lemon trees thrive in warm climates with ample sunlight and moderate humidity. They require well-drained, fertile soil and regular watering. Proper planting, pruning, and fertilization are essential for healthy growth and abundant fruit production. Regular monitoring for pests and diseases helps maintain tree health. By following these guidelines, you can enjoy a continuous harvest of fresh, flavorful lemons.`,
    },
    Mushroom: {
      ind:7,
      max_temp: 24,
      min_temp: 12,
      max_brightness_level: 0.1,
      min_brightness_level: 0.01,
      max_humidity: 95,
      min_humidity: 85,
      seed_description: `Mushrooms thrive in dark, moist environments with controlled temperatures. They require high humidity and grow best on prepared substrates. Proper hygiene and environmental control are essential to prevent contamination. With proper care, mushrooms can provide a bountiful and nutritious harvest.`,
    },
  };
  